### ISSUE TITLE
And the Beta Release?

### ISSUE THREAD

**Issue by CanalYT** [ArdenButterfield/Maim#60]
Hello, do you upload a release if you think it is necessary? :)

**Comment by ArdenButterfield** [comment]
Hello! All releases will be available here: https://github.com/ArdenButterfield/Maim/releases
The most recent release is still v1.0.0, which is here: https://github.com/ArdenButterfield/Maim/releases/tag/v1.0.0

**Comment by CanalYT** [comment]
I'm referring of the Versions with CLAP support and OggVorbis Codecs builts. :\
